---
# tasks file for setting up an assetto server on ubuntu20.04
- include: ssh_port_fallback.yml
- include: harden.yml
#  become: true
  when: harden_os
  tags: harden

- include: docker.yml
#  become: true
#  apply tags,become
#  when: harden_os
  tags: install-docker

- include: rocketchat.yml
#  become: true
#  apply tags,become
#  when: harden_os
#  tags: harden
