---
# tasks file for setting up a rocketchat server on ubuntu20.04
- include: ssh_port_fallback.yml

- include: harden.yml
#  become: true
  when: harden_os
  tags: harden

- include: docker.yml
  tags: install-docker

- include: rocketchat.yml
