---
# tasks file for setting up a rocketchat server on ubuntu20.04

- name: Include docker.yml task list
  ansible.builtin.import_tasks:
    file: docker.yml
  tags: install-docker

- name: Include rocketchat.yml task list
  ansible.builtin.import_tasks:
    file: rocketchat.yml
  tags: rocketchat
